feat: восстановление пароля
NewShiftStudio/gour-auth-service pull request #5
Opened 2022-09-12 16:23 UTC by avorokhta

2022-09-13 08:49 UTC, mirageN1349 requested changes

2022-09-13 08:49 UTC, mirageN1349 commented on back/src/features/auth/auth.service.ts
> +      console.log(error);
console.error

2022-09-13 08:49 UTC, mirageN1349 commented on back/src/features/auth/auth.service.ts
> +    const updatedUser = await this.userService.updateOne(candidate.id, {
вместо updateOne используй save

2022-09-13 08:49 UTC, mirageN1349 commented on back/src/features/auth/auth.service.ts
> +    console.log('dto', dto);
console.log

2022-09-20 08:22 UTC, avorokhta commented on back/src/features/auth/auth.service.ts
> +    const updatedUser = await this.userService.updateOne(candidate.id, {
это же метод из сервиса, он внутри себя и так делает save

2022-09-20 08:22 UTC, avorokhta commented on back/src/features/auth/auth.service.ts
> +    const updatedUser = await this.userService.updateOne(candidate.id, {
> вместо updateOne используй save
это же метод из сервиса, он внутри себя и так делает save

2022-12-19 11:38 UTC, mirageN1349 commented
Task linked: [CU-31mnrh9 Коды подтверждения приходят с почты New Shift](https://app.clickup.com/t/31mnrh9)

2022-12-19 11:39 UTC, mirageN1349 commented
Task linked: [CU-47ze3d2 Не приходит письмо с паролем администратора](https://app.clickup.com/t/47ze3d2)

2022-12-21 09:31 UTC, merged